kind: ConfigMap
apiVersion: v1
metadata:
  name: kube-flannel-cfg
  namespace: kube-system
  labels:
    application: flannel
data:
  cni-conf.json: |
    {
      "name": "podnet",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "isDefaultGateway": true,
            "hairpinMode": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "{{ .Cluster.ConfigItems.pod_cidr }}",
      "Backend": {
        "Type": "vxlan"
      }
    }
