{{ if ne .Cluster.ConfigItems.audittrail_url "" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: audittrail-adapter
  namespace: kube-system
  {{ if eq .ConfigItems.kube_aws_iam_controller_kube_system_enable "false"}}
    eks.amazonaws.com/role-arn: "arn:aws:iam::{{ .Cluster.InfrastructureAccount | getAWSAccountID }}:role/{{ .LocalID }}-audittrail-adapter"
  {{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: audittrail-adapter-privileged-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: audittrail-adapter
  namespace: kube-system
{{ end }}
